language: ruby
rvm:
- 2.6.5

before_install:
- chmod +x scripts/build.sh
- chmod +x scripts/deploy.sh

install: gem install dev-portfolio-blog html-proofer
script: scripts/build.sh

# branch whitelist
branches:
  only:
  - site     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: site
